#!/bin/sh

fuzzy_dirs="$HOME/Scripts/* $HOME/School/* $HOME/.vim/mysnippets/* $HOME/.bashrc $HOME/.xinitrc $HOME/.Xresources $HOME/.Xmodmap $HOME/Repos/* $HOME/Installs/* $HOME/Downloads/*"

fvi() { 
    [ -z "$1" ] && search="$fuzzy_dirs" || search="$1"
    fname="$(find $search -type d \( -name '.git' -o -name 'node_modules' -o -name 'venv' \) -prune -o -type f | fzf)"
    [ -z "$fname" ] || $EDITOR "$fname"
}
fcd() {
    [ -z "$1" ] && search="$fuzzy_dirs" || search="$1"
    dname="$(find $search -type d \( -name '.git' -o -name 'node_modules' -o -name 'venv' \) -prune -o -type d | fzf)"
    [ -z "$dname" ] || cd "$dname"
}
