#!/bin/sh


fvi() { 
    [ -z "$1" ] && search="$FUZZY_DIRS" || search="$1"
    fname="$(find $search -type d \( -name '.git' -o -name 'node_modules' -o -name 'venv' \) -prune -o -type f | fzf)"
    [ -z "$fname" ] || $EDITOR "$fname"
}
fcd() {
    [ -z "$1" ] && search="$FUZZY_DIRS" || search="$1"
    dname="$(fd . -t d $FUZZY_DIRS | fzf)"
    [ -z "$dname" ] || cd "$dname"
}
