#!/bin/bash

# https://unix.stackexchange.com/questions/37258/refresh-reload-active-browser-tab-from-command-line

BROWSER=$1
RELOAD_KEY="CTRL+R" 

CURWINDOW=$(xdotool getactivewindow)

xdotool search --name ${BROWSER} windowactivate --sync
xdotool search --name ${BROWSER} key --clearmodifiers ${RELOAD_KEY}
