#!/bin/sh

volume="$(amixer sget Master | grep 'Mono:' | awk -F'[][]' '{ print $2  }')"

icon=""
[ ${volume%\%} -gt "0" ] && icon="" 
[ ${volume%\%} -gt "50" ] && icon="" 
[ ${volume%\%} -gt "75" ] && icon="" 
echo -e "$icon $volume"

