#!/bin/sh

# Audio status for pulseaudio with pulsemixer

volume="$(pulsemixer --get-volume | awk '{ print $1 }')"

icon=""
[ "$volume" -gt "0" ] && icon="" 
[ "$volume" -gt "50" ] && icon="" 
[ "$volume" -gt "75" ] && icon="" 

[ "$(pulsemixer --get-mute)" = 1 ] && icon="ﱝ" && volume="XX"

printf "$icon $volume%%"
