#!/bin/sh

LANG=ja_JP.UTF-8
# dte="$(date +"%B%d日(%a)%H:%M")"
b="$(date +"%-m" | xargs printf '%02x')"
d="$(date +"%-d" | xargs printf '%02x')"
w="$(date +"%a")"
h="$(date +"%-H" | xargs printf '%02x')"
m="$(date +"%-M" | xargs printf '%02x')"

echo " ${b}月${d}日(${w})0x${h}:${m}"
