#!/bin/sh

# This is a simple launcher script for Taskell

boards_path="$HOME/.config/taskell/boards/"
(
    cd "$boards_path"
    board=$(ls -1 | dmenu -i -p "Choose board to open") 
    [ -z "$board" ] && exit 1

    st -e taskell "$board"
)
