#!/bin/sh

bat0="$(cat /sys/class/power_supply/BAT0/capacity)"
bat1="$(cat /sys/class/power_supply/BAT1/capacity)"
stat="$(cat /sys/class/power_supply/BAT0/status)"

status="?"
[ "$stat" = "Charging" ] && status="C"
[ "$stat" = "Discharging" ] && status="D"

icon=""
[ "$bat0" -gt "13" ] && icon=""
[ "$bat0" -gt "38" ] && icon=""
[ "$bat0" -gt "63" ] && icon=""
[ "$bat0" -gt "88" ] && icon=""

to_hex() {
    echo "${1} * 255 / 100" | bc | xargs printf '%02X'
}

echo "$icon ${status}$(to_hex $bat0)%:$(to_hex $bat1)%"
