#!/bin/sh
# some docker shorthands
# USAGE: source this script in [shell]rc file

d() {
    case $1 in
        p) docker ps "${@:2}";;
        c) docker container "${@:2}";;
        v) docker volume "${@:2}";;
        n) docker network "${@:2}";;
        i) docker images "${@:2}";;
        *) docker "$@"
    esac
}

dc() {
    case $1 in
        u) docker-compose up "${@:2}";;
        d) docker-compose down "${@:2}";;
        *) docker-compose "$@"
    esac
}
