#!/bin/sh

xrandr --newmode "1920x1080_60.00" 172.80  1920 2040 2248 2576  1080 1081 1084 1118  -HSync +Vsync
xrandr --addmode VGA1 "1920x1080_60.00"
xrandr --auto --output VGA1 --mode 1920x1080_60.00 --right-of LVDS1

# redshift
redshift -x
redshift -m randr:crtc=0 -O 3000
redshift -m randr:crtc=1 -O 5000

# need to reset wallpaper too
setwallpaper
