#!/bin/sh

get_json() {
    cat - | python3 -c "import sys, json; print(json.load(sys.stdin)['$1'])"
}

while read line; do
    icon="$(echo $line | get_json app_icon)"
    msg="$(echo $line | get_json summary)"
    herbe "$icon $msg" &
done
