#!/bin/sh

[ -z "$1" ] && printf "screenshot =-=-=-=-=\n-f for fullscreen screenshot\n-w for windowed screenshot\n" && exit 1

screen_dir="$HOME/Data/screenshots" # no ending slash

screen_name="$(printf "" | dmenu -p 'Screenshot name:')" # dmenu problem where it doesnt show up unless an input is given
[ -z "$screen_name" ] && screen_name="screen_$(date +'%m%d%H%M')"

screen_name="$screen_dir/$screen_name.png"

sleep 0.3

case $1 in
    -f|--full) scrot "$screen_name" && notify-send "Fullscreen screenshot taken - $screen_name" -i "";;
    -b|--box) scrot -s "$screen_name" && notify-send "Windowed screenshot taken - $screen_name" -i "";;
esac
