#!/bin/sh

# PINOSTRAP =-=-=-=-=-=
# shell script to bootstrap a simple system and copy over my dots
#
# this script will be debian based but it should be easy to modify
# the commands to fit the system
#
# pinostrap is destructive and will override preexisting config files

# user config vars =-=-=-=-=-=-=-=
packages="wget curl git make gcc"
home_dirs="Data Downloads Installs Music Notes Repos Scripts Temp"
dotrepo="$HOME/.dotfiles"
included_dotfiles=".vimrc"

mkdir "$home_dirs"

# install packages
sudo apt-get update -y
sudo apt-get install -y "$packages"

# init dotfiles bare repo
alias dotfiles="git --git-dir=$dotrepo --work-tree=$HOME"
git init --bare "$dotrepo"
dotfiles remote add github https://github.com/MrPicklePinosaur/dotfiles
dotfiles config --local status.showUntrackedFiles no
dotfiles config --local core.sparsecheckout true
echo "$included_dotfiles" > "$dotrepo/info/sparse-checkout"
dotfiles pull github master
# also find out how to pull and override local changes

